FROM docker.io/ubuntu:noble

ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8

# -------------------- LaTeX --------------------

ARG TECTONIC_VER="0.15.0"
ARG TECTONIC_SRC="https://github.com/tectonic-typesetting/tectonic/releases/download/tectonic%40${TECTONIC_VER}/tectonic-${TECTONIC_VER}-x86_64-unknown-linux-gnu.tar.gz"


WORKDIR /usr/src/tectonic

ADD $TECTONIC_SRC .

RUN tar -xvzf tectonic-*.tar.gz && rm tectonic-*.tar.gz

ENV PATH="$PATH:/usr/src/tectonic"


RUN apt-get update && \
    apt-get install -y --no-install-recommends libgraphite2-3 ca-certificates && \
    apt-get install -y --no-install-recommends python3-pygments fontconfig biber lcdf-typetools && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------- Development --------------------

ARG TEXLAB_SRC="https://github.com/latex-lsp/texlab/releases/latest/download/texlab-x86_64-linux.tar.gz"

ARG GOTASK_SRC="https://github.com/go-task/task/releases/latest/download/task_linux_amd64.tar.gz"


WORKDIR /usr/src/texlab

ADD $TEXLAB_SRC .

RUN tar -xvzf texlab-*.tar.gz && rm texlab-*.tar.gz

ENV PATH="$PATH:/usr/src/texlab"


WORKDIR /usr/src/gotask

ADD $GOTASK_SRC .

RUN tar -xvzf task_*.tar.gz && rm task_*.tar.gz

ENV PATH="$PATH:/usr/src/gotask"
ENV TASK_TEMP_DIR="/tmp/.task"


RUN apt-get update && \
    apt-get install -y --no-install-recommends 7zip-standalone && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
