# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

env:
  PROJECT_DIR: "{{ .USER_WORKING_DIR }}"

tasks:
  check:
    internal: true
    preconditions:
      - sh: test -f {{ .PROJECT_DIR }}/main.tex
        msg: "Error: project entrypoint main.tex not found !"

  compile:
    desc: "Compile the project"
    dir: "{{ .TASKFILE_DIR }}"
    vars:
      COMPILE_DIR: build/{{ base .PROJECT_DIR }}/
    deps:
      - check
    preconditions:
      - test -d {{ .COMPILE_DIR }} || mkdir -p {{ .COMPILE_DIR }}
    cmds:
      - tectonic -X compile {{ .PROJECT_DIR }}/main.tex --outdir {{ .COMPILE_DIR }} -Z shell-escape -Z search-path=resources/ --synctex --keep-logs --keep-intermediates

  archive:
    desc: "Archive the project"
    dir: "{{ .TASKFILE_DIR }}"
    vars:
      ARCHIVE_DIR: dist/{{ base .PROJECT_DIR }}/
    deps:
      - check
    preconditions:
      - test -d {{ .ARCHIVE_DIR }} || mkdir -p {{ .ARCHIVE_DIR }}
    cmds:
      - 7zz a {{ .ARCHIVE_DIR }}/{{ base .PROJECT_DIR }}-{{ now | date "20060102-150405" }}.zip {{ .PROJECT_DIR }}/* ./resources/*
